# Generated by Django 5.0.6 on 2024-06-05 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "description",
                    models.TextField(blank=True, default="Another quiz!", null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                ("number_of_questions", models.IntegerField()),
                (
                    "time",
                    models.IntegerField(
                        help_text="Viktorinaning davomiyligi (daqiqalarda)"
                    ),
                ),
                (
                    "required_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Viktorinadan o'tish uchun necha foiz ball kerak bo'ladi",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        help_text="Viktorinaning qiyinligi",
                        max_length=6,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Viktorina baholanadigan mavzu",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizes",
                        to="courses.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizes",
            },
        ),
    ]
