# Generated by Django 4.2.13 on 2024-10-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_subcategory_course_type"),
        ("quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="subcategory",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.subcategory",
            ),
        ),
    ]
