# Generated by Django 4.2.13 on 2024-10-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_subcategory_course_type"),
        ("quiz_app", "0002_quiz_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="topic",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="Viktorina baholanadigan mavzu",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizes",
                to="courses.subcategory",
            ),
        ),
    ]
