# Generated by Django 4.2.13 on 2024-10-10 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz_app", "0003_remove_quiz_topic_alter_quiz_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="teacher",
            field=models.ForeignKey(
                default=None,
                help_text="Viktorinani yaratgan o'qituvchi",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
