# Generated by Django 5.0.6 on 2024-06-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="users/")),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("Student", "Student"),
                            ("Teacher", "Teacher"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("bio", models.CharField(max_length=200)),
                ("liked_videos_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                (
                    "saved_playlists",
                    models.ManyToManyField(
                        blank=True,
                        related_name="saved_by_users",
                        to="courses.subcategory",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("Biologiya", "Biology"),
                            ("Kimyo", "Chemistry"),
                            ("Physics", "Physics"),
                            ("Matematika", "Math"),
                            ("Ingliz tili", "English"),
                            ("Tarix", "History"),
                            ("Geografiya", "Geography"),
                            ("Computer Science", "Computer Science"),
                            ("Adabiyot", "Literature"),
                            ("San'at", "Art"),
                            ("Musiqa", "Music"),
                        ],
                        default="Other",
                        max_length=200,
                    ),
                ),
                ("bio", models.TextField()),
                ("courses_num", models.IntegerField(default=0)),
                ("videos_num", models.IntegerField(default=0)),
                ("student_num", models.IntegerField(default=0)),
                ("likes_num", models.IntegerField(default=0)),
                ("comments_num", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_teachers",
                        to="users.profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
