# Generated by Django 5.0 on 2024-05-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="job",
            field=models.CharField(
                choices=[
                    ("Other", "Other"),
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("Biologiya", "Biology"),
                            ("Kimyo", "Chemistry"),
                            ("Physics", "Physics"),
                            ("Matematika", "Math"),
                            ("Ingliz tili", "English"),
                            ("Tarix", "History"),
                            ("Geografiya", "Geography"),
                            ("Computer Science", "Computer Science"),
                            ("Adabiyot", "Literature"),
                            ("San'at", "Art"),
                            ("Musiqa", "Music"),
                        ],
                        default="Other",
                        max_length=200,
                    ),
                ),
                ("student_num", models.IntegerField(default=0)),
                ("bio", models.TextField()),
                ("likes_num", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
