# Generated by Django 4.2.13 on 2024-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="0 dan 5 gacha baho bering"
            ),
        ),
    ]
