# Generated by Django 4.2.13 on 2024-08-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
