# Generated by Django 5.0 on 2024-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_job_alter_profile_user_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="courses_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teachers",
            name="videos_num",
            field=models.IntegerField(default=0),
        ),
    ]
