# Generated by Django 5.0 on 2024-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_teachers_courses_num_teachers_videos_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="comments_num",
            field=models.IntegerField(default=0),
        ),
    ]
