# Generated by Django 4.2.13 on 2024-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
