# Generated by Django 5.0 on 2024-05-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_teachers_comments_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_teachers",
                to="users.profile",
            ),
            preserve_default=False,
        ),
    ]
