# Generated by Django 5.0 on 2024-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_subcategory_descriptions"),
        ("users", "0005_teachers_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_playlists",
            field=models.ManyToManyField(
                related_name="saved_by_users", to="courses.subcategory"
            ),
        ),
    ]
