# Generated by Django 4.2.13 on 2024-10-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_adminearnings_teachers_earnings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name="AdminEarnings",
        ),
        migrations.RenameField(
            model_name="teachers",
            old_name="earnings",
            new_name="income",
        ),
    ]
