# Generated by Django 5.0 on 2024-05-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_profile_saved_playlists"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="liked_videos_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
