# Generated by Django 5.0.6 on 2024-06-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="users.teachers",
            ),
        ),
        migrations.AddField(
            model_name="videos",
            name="likes_num",
            field=models.ManyToManyField(
                blank=True, related_name="videos_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="videos",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.subcategory"
            ),
        ),
        migrations.AddField(
            model_name="likes",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.videos"
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="courses.videos",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="likes",
            unique_together={("user", "video")},
        ),
    ]
