# Generated by Django 5.0 on 2024-05-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="courses_count",
        ),
        migrations.RemoveField(
            model_name="category",
            name="students_count",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="courses_count",
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategory",
                to="courses.category",
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.subcategory",
            ),
        ),
    ]
