# Generated by Django 4.2.13 on 2024-06-06 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
