# Generated by Django 5.0 on 2024-05-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_category_courses_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="courses.category",
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.subcategory"
            ),
        ),
    ]
