# Generated by Django 5.0 on 2024-05-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_subcategory_category_alter_videos_subcategory"),
        ("users", "0004_teachers_comments_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="users.teachers",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videos",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videos",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="videos",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.subcategory",
            ),
        ),
    ]
