# Generated by Django 4.2.13 on 2024-08-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_likes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="is_payment",
            field=models.BooleanField(default=False),
        ),
    ]
