# Generated by Django 5.0 on 2024-05-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_comments_options_comments_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="courses.comments",
            ),
        ),
    ]
