# Generated by Django 4.2.13 on 2024-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_subcategory_is_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="cover_video",
            field=models.ImageField(default="static/images/post-1-1.png", upload_to=""),
        ),
    ]
