# Generated by Django 5.0 on 2024-05-29 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_comments_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="parent",
        ),
    ]
