# Generated by Django 4.2.13 on 2024-09-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_videos_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="old_price",
            field=models.IntegerField(default=0),
        ),
    ]
