# Generated by Django 4.2.13 on 2024-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_videos_cover_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="price",
            field=models.BigIntegerField(default=0),
        ),
    ]
