# Generated by Django 4.2.13 on 2024-09-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_subcategory_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="course_type",
            field=models.CharField(
                choices=[("Free", "Free"), ("Paid", "Paid")],
                default="Free",
                max_length=200,
            ),
        ),
    ]
