# Generated by Django 4.2.13 on 2024-08-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_balance"),
        ("courses", "0006_subcategory_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="purchased_users",
            field=models.ManyToManyField(
                blank=True, related_name="purchased_courses", to="users.profile"
            ),
        ),
    ]
