# Generated by Django 5.0 on 2024-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_remove_comments_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="descriptions",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
