# Generated by Django 4.2.13 on 2024-10-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_subcategory_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="purchased_count",
            field=models.IntegerField(default=0),
        ),
    ]
