# Generated by Django 5.0 on 2024-05-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_subcategory_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videos",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
