# Generated by Django 5.0 on 2024-05-30 10:19

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_videos_comments_count_videos_likes_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="videos",
            name="likes_count",
        ),
        migrations.AddField(
            model_name="videos",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
