# Generated by Django 5.0 on 2024-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_remove_videos_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="comment_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videos",
            name="likes_num",
            field=models.IntegerField(default=0),
        ),
    ]
