# Generated by Django 5.0 on 2024-05-31 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos",
            name="likes_num",
        ),
        migrations.AddField(
            model_name="videos",
            name="likes",
            field=models.ManyToManyField(
                related_name="videos_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Likes",
        ),
    ]
