# Generated by Django 5.0 on 2024-06-01 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_remove_videos_likes_videos_likes_num_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videos",
            name="likes_num",
        ),
        migrations.AddField(
            model_name="videos",
            name="likes_num",
            field=models.ManyToManyField(
                blank=True, related_name="videos_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
