# Generated by Django 5.0 on 2024-06-01 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_remove_videos_likes_num_videos_likes_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="videos",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
